### ISSUE TITLE
Core dumps are committed to Git

### ISSUE THREAD

**Issue by jacobilsoe** [rtcTo/rtc2git#67] opened 2015-09-23 07:06 UTC
When Rtc crashes it leaves core dump files (and others) in the working directory. These files are then committed to Git.

**Comment by WtfJoke** [comment] 2015-09-23 14:51
I never experienced that. What you mean with rtc crashes? You mean lscm/scm crashes? But why it should leave dump files in the work directory? Usually it has its own directory with log files and so on.

Can you reproduce it?

**Comment by jacobilsoe** [comment] 2015-09-23 17:41
Yes, I mean scm. I don't know why it left a core dump there. I did not investigate it any further but I will provide more info if it happens again.

**Comment by WtfJoke** [comment] 2015-09-24 18:15
Sounds strange... Let me know when you know more details.

**Comment by ohumbel** [comment] 2015-09-24 19:11
@jacobilsoe how are those core dump files named? Maybe we could add patterns to the top-level .gitignore we create when starting the migration?

**Comment by jacobilsoe** [comment] 2015-10-07 09:13
Just got it again. In both cases the problem was: Detail "java/lang/OutOfMemoryError" "Java heap space"

Here are the files that got committed to Git:

07-10-2015  10:59       774.591.748 core.20151006.115559.7756.0001.dmp
07-10-2015  10:59       774.672.932 core.20151006.115602.7756.0003.dmp
07-10-2015  10:59        54.180.351 heapdump.20151006.115559.7756.0002.phd
07-10-2015  11:00        54.180.351 heapdump.20151006.115602.7756.0005.phd
07-10-2015  11:00           969.457 javacore.20151006.115559.7756.0004.txt
07-10-2015  11:00           948.603 javacore.20151006.115602.7756.0007.txt
07-10-2015  10:59           355.732 Snap.20151006.115559.7756.0006.trc
07-10-2015  10:59            36.244 Snap.20151006.115602.7756.0008.trc

**Comment by WtfJoke** [comment] 2015-10-07 14:42
Maybe it helps if you ask for advice on [the jazz net forum](https://jazz.net/forum/questions/)... I never experienced such an issue. Not sure if they can help you, but at least it would be the place to address this issue.

However I would try to increase the memory of the rtc scm client.
In the scm.ini you can increase -Xmx512m to a value of your desire (-Xmx1024m for example).
Another idea would be to use jdk8 as vm, because it handles memory in a more relaxed way in my opinion (as long as you have enough memory :sweat_smile:).



Not sure how we should continue with this issue, though.

Either we add .*dmp, *.phd and *.trc to gitignore. 
But the .txt files would be still present and Im not sure if we should really check for that filenamepattern.

At the moment I think the best way to solve this is that you add these file extensions in your settings file to the IgnoreFileExtensions --> https://github.com/rtcTo/rtc2git/blob/develop/config.ini.sample#L61 (eg. IgnoreFileExtensions = .dmp, .phd, .trc)

Or what are your thoughts about it? 
Maybe @ohumbel has also some idea as well, as soon as he is back from his vacations :)

**Comment by WtfJoke** [comment] 2015-11-16 09:18
@jacobilsoe Were you able to solve it using my given workaround or were able to find the reason why you got a memory leak by using jazz forums?

Else I would close this issue during the next days, because I cannot reproduce it.

**Comment by jacobilsoe** [comment] 2015-11-16 10:44
Sorry for not getting back on this one. I tried different things and managed to make it somewhat stable. I still had issues now and then though. I ended up manually deleting the dump files from the migrated repo. It is fine with me to close the issue.

**Comment by WtfJoke** [comment] 2015-11-16 11:19
Thanks for your feedback. I thought with ignoring them should work out without any problems.

**Closed by WtfJoke** 2015-11-16 11:19 UTC
Labels: more info
