### ISSUE TITLE
RTC changeset comments with $variable resolve to blank in git commit comment

### ISSUE THREAD

**Issue by AdamBrousseau** [rtcTo/rtc2git#97] opened 2016-03-15 15:19 UTC
RTC changeset comments and work item summaries can contain variable names, for example, "fix thing related to $MYVARIABLE in some file". When this change is committed in Git, the variable resolves to nothing/blank. I.e. "fix thing related to  in some file".
It could pose some confusion for users looking back at the Git history in the future.

**Comment by WtfJoke** [comment] 2016-03-15 15:56
Hi Adam,

Thanks for this hint. I guess the $MYVARIABLE is resolved by the shell (or git?) to a nonexisting variable?

Do you know how to avoid this? I guess it needs some kind of escaping?

**Comment by AdamBrousseau** [comment] 2016-03-15 17:11
Yes I assume that is what is happening. I have not yet had a chance to investigate where it happens or if there is a simple fix. I thought I would raise the issue in the meantime.

**Comment by pbhandari** [comment] 2016-03-17 11:57
I wonder if it isn't `shell.py::quote` that's at fault here.

We use that in `gitFunction.py::getcommitcommand` to quote the shell command that we want to use, and then executing it via the shell

So, we'd be executing `git commit -m "Commit msg with $VAR_NAME" `  which causes the shell to attempt to resolve `$VAR_NAME`, not find it and resolve it to an empty string.

**Comment by WtfJoke** [comment] 2016-05-16 15:26
> I think if we were to replace shell.py::quote with shlex.quote it might fix the issue fairly easily...

Have you or adam tested this? For some reason I didnt use shlex.quote... I just have forgotten why.

**Comment by pbhandari** [comment] 2016-05-26 15:20
@WtfJoke:  I can't speak for Adam, but when my team was porting the stream to git we used `shlex.quote`.  And it seemed to work just fine.

If `shlex.quote` won't work ... the other option would be to modify your `quote` thusly:
```
>>> import subprocess
>>> commit = "Can't touch $this"
>>> def quote(stringtoquote):
...     stringtoquote = stringtoquote.replace('\"', "'")  # replace " with '
...     stringtoquote = stringtoquote.replace('$', '\\$') # escape out the $
...     quotedstring = '\"' + stringtoquote + '\"'
...     return quotedstring
... 
>>> subprocess.call("echo " + quote(commit), shell=True)
Can't touch $this
0
```

Of course, this only fixes _this_ specific issue

**Comment by pbhandari** [comment] 2016-07-02 13:55
Huh ... so it looks like that `shlex.quote` is only available on python 3.3+  which is probably why you didn't use `shlex.quote`.

**Comment by ohumbel** [comment] 2016-10-06 06:26
The syntax to prevent `$VAR` expansion in the shell would be: `"\$"VAR`.

I will try to reproduce this with my (still working) jazz.net account.

**Comment by ohumbel** [comment] 2016-10-06 20:48
I have a prototype working (from Hackergarten Lucerne):

The RTC commit text is:
`38691: Some code changes - the commit having a $variable in his comment`

The log is showing:
`22:33:25 - Executed Command: "git commit -m 'RTC-38691: Some code changes - the commit having a '\"\$"'variable in his comment' ..."`

and using `git log` I see:
`RTC-38691: Some code changes - the commit having a $variable in his comment`

**Closed** 2016-10-17 14:53 UTC
Labels: bug, nicetohave
